builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    replacements:
      darwin: macos
