builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}
archives:
  - format: binary
    replacements:
      amd64: intel
      arm64: m1
      darwin: macos
