builds:
  - env:
      - CGO_ENABLED=1
    goos:
      # - linux # TODO
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/feeltheajf/ztman/config.Version={{.Version}}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
